version: '3.3'
services:
    web:
        container_name: web
        build: .
        ports:
            - '3000:3000'
        networks:
            api_network:
                ipv4_address: 172.20.128.1

networks:
    api_network:
        external: true